# Configurations
title:            LBardel Blog
longtitle:        Tinkering and Hacking
author:           Me, LBardel
email:            tt@tt.tt
description: >
  Dumping my projects here, maybe someone could find something usefull in this pile of trash ;)

version:          1.0
gitbook_version:  3.2.3

url:              'https://github.com/LBardel/LBardel.github.io/'
baseurl:          '/'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
